/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  "group-detail": () => import("@/views/group-detail/[gId].vue"),
  "ops_announcements-list": () => import("@/views/ops/announcements-list/index.vue"),
  "ops_announcements-send": () => import("@/views/ops/announcements-send/index.vue"),
  "ops_api-monitor": () => import("@/views/ops/api-monitor/index.vue"),
  "ops_client-versions": () => import("@/views/ops/client-versions/index.vue"),
  ops_feedback: () => import("@/views/ops/feedback/index.vue"),
  "ops_friend-backfill": () => import("@/views/ops/friend-backfill/index.vue"),
  "ops_official-accounts": () => import("@/views/ops/official-accounts/index.vue"),
  ops_splash: () => import("@/views/ops/splash/index.vue"),
  "ops_wallet-notice": () => import("@/views/ops/wallet-notice/index.vue"),
  privacy_album: () => import("@/views/privacy/album/index.vue"),
  privacy_contacts: () => import("@/views/privacy/contacts/index.vue"),
  privacy_stats: () => import("@/views/privacy/stats/index.vue"),
  risk_complaints: () => import("@/views/risk/complaints/index.vue"),
  risk_devices: () => import("@/views/risk/devices/index.vue"),
  "risk_group-logs": () => import("@/views/risk/group-logs/index.vue"),
  "risk_groups-index": () => import("@/views/risk/groups-index/index.vue"),
  risk_messages: () => import("@/views/risk/messages/index.vue"),
  risk_relations: () => import("@/views/risk/relations/index.vue"),
  "system_admin-login-logs": () => import("@/views/system/admin-login-logs/index.vue"),
  system_advanced: () => import("@/views/system/advanced/index.vue"),
  "system_audit-logs": () => import("@/views/system/audit-logs/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_profile: () => import("@/views/system/profile/index.vue"),
  "user-detail": () => import("@/views/user-detail/[userUid].vue"),
  "users-index": () => import("@/views/users-index/index.vue"),
  "users_generation-tasks": () => import("@/views/users/generation-tasks/index.vue"),
  "users_login-records": () => import("@/views/users/login-records/index.vue"),
  wallet_currencies: () => import("@/views/wallet/currencies/index.vue"),
  "wallet_exchange-config": () => import("@/views/wallet/exchange-config/index.vue"),
  wallet_exchanges: () => import("@/views/wallet/exchanges/index.vue"),
  "wallet_fee-config": () => import("@/views/wallet/fee-config/index.vue"),
  wallet_ledger: () => import("@/views/wallet/ledger/index.vue"),
  "wallet_life-payments_orders": () => import("@/views/wallet/life-payments/orders/index.vue"),
  "wallet_life-payments_providers": () => import("@/views/wallet/life-payments/providers/index.vue"),
  "wallet_life-payments_tasks": () => import("@/views/wallet/life-payments/tasks/index.vue"),
  "wallet_life-payments_workers": () => import("@/views/wallet/life-payments/workers/index.vue"),
  "wallet_limit-config": () => import("@/views/wallet/limit-config/index.vue"),
  wallet_recharges: () => import("@/views/wallet/recharges/index.vue"),
  "wallet_red-packets": () => import("@/views/wallet/red-packets/index.vue"),
  "wallet_sweep-logs": () => import("@/views/wallet/sweep-logs/index.vue"),
  wallet_transfers: () => import("@/views/wallet/transfers/index.vue"),
  wallet_treasury: () => import("@/views/wallet/treasury/index.vue"),
  wallet_withdraws: () => import("@/views/wallet/withdraws/index.vue"),
};
