/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard'
    }
  },
  {
    name: 'group-detail',
    path: '/group-detail/:gId',
    component: 'layout.base$view.group-detail',
    props: true,
    meta: {
      title: 'group-detail',
      i18nKey: 'route.group-detail'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.base$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'ops',
    path: '/ops',
    component: 'layout.base',
    meta: {
      title: 'ops',
      i18nKey: 'route.ops'
    },
    children: [
      {
        name: 'ops_announcements-list',
        path: '/ops/announcements-list',
        component: 'view.ops_announcements-list',
        meta: {
          title: 'ops_announcements-list',
          i18nKey: 'route.ops_announcements-list'
        }
      },
      {
        name: 'ops_announcements-send',
        path: '/ops/announcements-send',
        component: 'view.ops_announcements-send',
        meta: {
          title: 'ops_announcements-send',
          i18nKey: 'route.ops_announcements-send'
        }
      },
      {
        name: 'ops_api-monitor',
        path: '/ops/api-monitor',
        component: 'view.ops_api-monitor',
        meta: {
          title: 'ops_api-monitor',
          i18nKey: 'route.ops_api-monitor'
        }
      },
      {
        name: 'ops_client-versions',
        path: '/ops/client-versions',
        component: 'view.ops_client-versions',
        meta: {
          title: 'ops_client-versions',
          i18nKey: 'route.ops_client-versions'
        }
      },
      {
        name: 'ops_feedback',
        path: '/ops/feedback',
        component: 'view.ops_feedback',
        meta: {
          title: 'ops_feedback',
          i18nKey: 'route.ops_feedback'
        }
      },
      {
        name: 'ops_friend-backfill',
        path: '/ops/friend-backfill',
        component: 'view.ops_friend-backfill',
        meta: {
          title: 'ops_friend-backfill',
          i18nKey: 'route.ops_friend-backfill'
        }
      },
      {
        name: 'ops_official-accounts',
        path: '/ops/official-accounts',
        component: 'view.ops_official-accounts',
        meta: {
          title: 'ops_official-accounts',
          i18nKey: 'route.ops_official-accounts'
        }
      },
      {
        name: 'ops_splash',
        path: '/ops/splash',
        component: 'view.ops_splash',
        meta: {
          title: 'ops_splash',
          i18nKey: 'route.ops_splash'
        }
      },
      {
        name: 'ops_wallet-notice',
        path: '/ops/wallet-notice',
        component: 'view.ops_wallet-notice',
        meta: {
          title: 'ops_wallet-notice',
          i18nKey: 'route.ops_wallet-notice'
        }
      }
    ]
  },
  {
    name: 'privacy',
    path: '/privacy',
    component: 'layout.base',
    meta: {
      title: 'privacy',
      i18nKey: 'route.privacy'
    },
    children: [
      {
        name: 'privacy_album',
        path: '/privacy/album',
        component: 'view.privacy_album',
        meta: {
          title: 'privacy_album',
          i18nKey: 'route.privacy_album'
        }
      },
      {
        name: 'privacy_contacts',
        path: '/privacy/contacts',
        component: 'view.privacy_contacts',
        meta: {
          title: 'privacy_contacts',
          i18nKey: 'route.privacy_contacts'
        }
      },
      {
        name: 'privacy_stats',
        path: '/privacy/stats',
        component: 'view.privacy_stats',
        meta: {
          title: 'privacy_stats',
          i18nKey: 'route.privacy_stats'
        }
      }
    ]
  },
  {
    name: 'risk',
    path: '/risk',
    component: 'layout.base',
    meta: {
      title: 'risk',
      i18nKey: 'route.risk'
    },
    children: [
      {
        name: 'risk_complaints',
        path: '/risk/complaints',
        component: 'view.risk_complaints',
        meta: {
          title: 'risk_complaints',
          i18nKey: 'route.risk_complaints'
        }
      },
      {
        name: 'risk_devices',
        path: '/risk/devices',
        component: 'view.risk_devices',
        meta: {
          title: 'risk_devices',
          i18nKey: 'route.risk_devices'
        }
      },
      {
        name: 'risk_group-logs',
        path: '/risk/group-logs',
        component: 'view.risk_group-logs',
        meta: {
          title: 'risk_group-logs',
          i18nKey: 'route.risk_group-logs'
        }
      },
      {
        name: 'risk_groups-index',
        path: '/risk/groups-index',
        component: 'view.risk_groups-index',
        meta: {
          title: 'risk_groups-index',
          i18nKey: 'route.risk_groups-index'
        }
      },
      {
        name: 'risk_messages',
        path: '/risk/messages',
        component: 'view.risk_messages',
        meta: {
          title: 'risk_messages',
          i18nKey: 'route.risk_messages'
        }
      },
      {
        name: 'risk_relations',
        path: '/risk/relations',
        component: 'view.risk_relations',
        meta: {
          title: 'risk_relations',
          i18nKey: 'route.risk_relations'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_admin-login-logs',
        path: '/system/admin-login-logs',
        component: 'view.system_admin-login-logs',
        meta: {
          title: 'system_admin-login-logs',
          i18nKey: 'route.system_admin-login-logs'
        }
      },
      {
        name: 'system_advanced',
        path: '/system/advanced',
        component: 'view.system_advanced',
        meta: {
          title: 'system_advanced',
          i18nKey: 'route.system_advanced'
        }
      },
      {
        name: 'system_audit-logs',
        path: '/system/audit-logs',
        component: 'view.system_audit-logs',
        meta: {
          title: 'system_audit-logs',
          i18nKey: 'route.system_audit-logs'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_profile',
        path: '/system/profile',
        component: 'view.system_profile',
        meta: {
          title: 'system_profile',
          i18nKey: 'route.system_profile'
        }
      }
    ]
  },
  {
    name: 'user-detail',
    path: '/user-detail/:userUid',
    component: 'layout.base$view.user-detail',
    props: true,
    meta: {
      title: 'user-detail',
      i18nKey: 'route.user-detail'
    }
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base',
    meta: {
      title: 'users',
      i18nKey: 'route.users'
    },
    children: [
      {
        name: 'users_generation-tasks',
        path: '/users/generation-tasks',
        component: 'view.users_generation-tasks',
        meta: {
          title: 'users_generation-tasks',
          i18nKey: 'route.users_generation-tasks'
        }
      },
      {
        name: 'users_login-records',
        path: '/users/login-records',
        component: 'view.users_login-records',
        meta: {
          title: 'users_login-records',
          i18nKey: 'route.users_login-records'
        }
      }
    ]
  },
  {
    name: 'users-index',
    path: '/users-index',
    component: 'layout.base$view.users-index',
    meta: {
      title: 'users-index',
      i18nKey: 'route.users-index'
    }
  },
  {
    name: 'wallet',
    path: '/wallet',
    component: 'layout.base',
    meta: {
      title: 'wallet',
      i18nKey: 'route.wallet'
    },
    children: [
      {
        name: 'wallet_currencies',
        path: '/wallet/currencies',
        component: 'view.wallet_currencies',
        meta: {
          title: 'wallet_currencies',
          i18nKey: 'route.wallet_currencies'
        }
      },
      {
        name: 'wallet_exchange-config',
        path: '/wallet/exchange-config',
        component: 'view.wallet_exchange-config',
        meta: {
          title: 'wallet_exchange-config',
          i18nKey: 'route.wallet_exchange-config'
        }
      },
      {
        name: 'wallet_exchanges',
        path: '/wallet/exchanges',
        component: 'view.wallet_exchanges',
        meta: {
          title: 'wallet_exchanges',
          i18nKey: 'route.wallet_exchanges'
        }
      },
      {
        name: 'wallet_fee-config',
        path: '/wallet/fee-config',
        component: 'view.wallet_fee-config',
        meta: {
          title: 'wallet_fee-config',
          i18nKey: 'route.wallet_fee-config'
        }
      },
      {
        name: 'wallet_ledger',
        path: '/wallet/ledger',
        component: 'view.wallet_ledger',
        meta: {
          title: 'wallet_ledger',
          i18nKey: 'route.wallet_ledger'
        }
      },
      {
        name: 'wallet_life-payments',
        path: '/wallet/life-payments',
        meta: {
          title: 'wallet_life-payments',
          i18nKey: 'route.wallet_life-payments'
        },
        children: [
          {
            name: 'wallet_life-payments_orders',
            path: '/wallet/life-payments/orders',
            component: 'view.wallet_life-payments_orders',
            meta: {
              title: 'wallet_life-payments_orders',
              i18nKey: 'route.wallet_life-payments_orders'
            }
          },
          {
            name: 'wallet_life-payments_providers',
            path: '/wallet/life-payments/providers',
            component: 'view.wallet_life-payments_providers',
            meta: {
              title: 'wallet_life-payments_providers',
              i18nKey: 'route.wallet_life-payments_providers'
            }
          },
          {
            name: 'wallet_life-payments_tasks',
            path: '/wallet/life-payments/tasks',
            component: 'view.wallet_life-payments_tasks',
            meta: {
              title: 'wallet_life-payments_tasks',
              i18nKey: 'route.wallet_life-payments_tasks'
            }
          },
          {
            name: 'wallet_life-payments_workers',
            path: '/wallet/life-payments/workers',
            component: 'view.wallet_life-payments_workers',
            meta: {
              title: 'wallet_life-payments_workers',
              i18nKey: 'route.wallet_life-payments_workers'
            }
          }
        ]
      },
      {
        name: 'wallet_limit-config',
        path: '/wallet/limit-config',
        component: 'view.wallet_limit-config',
        meta: {
          title: 'wallet_limit-config',
          i18nKey: 'route.wallet_limit-config'
        }
      },
      {
        name: 'wallet_recharges',
        path: '/wallet/recharges',
        component: 'view.wallet_recharges',
        meta: {
          title: 'wallet_recharges',
          i18nKey: 'route.wallet_recharges'
        }
      },
      {
        name: 'wallet_red-packets',
        path: '/wallet/red-packets',
        component: 'view.wallet_red-packets',
        meta: {
          title: 'wallet_red-packets',
          i18nKey: 'route.wallet_red-packets'
        }
      },
      {
        name: 'wallet_sweep-logs',
        path: '/wallet/sweep-logs',
        component: 'view.wallet_sweep-logs',
        meta: {
          title: 'wallet_sweep-logs',
          i18nKey: 'route.wallet_sweep-logs'
        }
      },
      {
        name: 'wallet_transfers',
        path: '/wallet/transfers',
        component: 'view.wallet_transfers',
        meta: {
          title: 'wallet_transfers',
          i18nKey: 'route.wallet_transfers'
        }
      },
      {
        name: 'wallet_treasury',
        path: '/wallet/treasury',
        component: 'view.wallet_treasury',
        meta: {
          title: 'wallet_treasury',
          i18nKey: 'route.wallet_treasury'
        }
      },
      {
        name: 'wallet_withdraws',
        path: '/wallet/withdraws',
        component: 'view.wallet_withdraws',
        meta: {
          title: 'wallet_withdraws',
          i18nKey: 'route.wallet_withdraws'
        }
      }
    ]
  }
];
