/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteRecordRaw, RouteComponent } from 'vue-router';
import type { ElegantConstRoute } from '@elegant-router/vue';
import type { RouteMap, RouteKey, RoutePath } from '@elegant-router/types';

/**
 * transform elegant const routes to vue routes
 * @param routes elegant const routes
 * @param layouts layout components
 * @param views view components
 */
export function transformElegantRoutesToVueRoutes(
  routes: ElegantConstRoute[],
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  return routes.flatMap(route => transformElegantRouteToVueRoute(route, layouts, views));
}

/**
 * transform elegant route to vue route
 * @param route elegant const route
 * @param layouts layout components
 * @param views view components
 */
function transformElegantRouteToVueRoute(
  route: ElegantConstRoute,
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  const LAYOUT_PREFIX = 'layout.';
  const VIEW_PREFIX = 'view.';
  const ROUTE_DEGREE_SPLITTER = '_';
  const FIRST_LEVEL_ROUTE_COMPONENT_SPLIT = '$';

  function isLayout(component: string) {
    return component.startsWith(LAYOUT_PREFIX);
  }

  function getLayoutName(component: string) {
    const layout = component.replace(LAYOUT_PREFIX, '');

    if(!layouts[layout]) {
      throw new Error(`Layout component "${layout}" not found`);
    }

    return layout;
  }

  function isView(component: string) {
    return component.startsWith(VIEW_PREFIX);
  }

  function getViewName(component: string) {
    const view = component.replace(VIEW_PREFIX, '');

    if(!views[view]) {
      throw new Error(`View component "${view}" not found`);
    }

    return view;
  }

  function isFirstLevelRoute(item: ElegantConstRoute) {
    return !item.name.includes(ROUTE_DEGREE_SPLITTER);
  }

  function isSingleLevelRoute(item: ElegantConstRoute) {
    return isFirstLevelRoute(item) && !item.children?.length && String(item.component || '').includes('$');
  }

  function getSingleLevelRouteComponent(component: string) {
    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);

    return {
      layout: getLayoutName(layout),
      view: getViewName(view)
    };
  }

  const vueRoutes: RouteRecordRaw[] = [];

  // add props: true to route
  if (route.path.includes(':') && !route.props) {
    route.props = true;
  }

  const { name, path, component, children, ...rest } = route;

  const vueRoute = { name, path, ...rest } as RouteRecordRaw;

  try {
    if (component) {
      if (isSingleLevelRoute(route)) {
        const { layout, view } = getSingleLevelRouteComponent(component);

        const singleLevelRoute: RouteRecordRaw = {
          path,
          component: layouts[layout],
          meta: {
            title: route.meta?.title || ''
          },
          children: [
            {
              name,
              path: '',
              component: views[view],
              ...rest
            } as RouteRecordRaw
          ]
        };

        return [singleLevelRoute];
      }

      if (isLayout(component)) {
        const layoutName = getLayoutName(component);

        vueRoute.component = layouts[layoutName];
      }

      if (isView(component)) {
        const viewName = getViewName(component);

        vueRoute.component = views[viewName];
      }

    }
  } catch (error: any) {
    console.error(`Error transforming route "${route.name}": ${error.toString()}`);
    return [];
  }

  // add redirect to child
  if (children?.length && !vueRoute.redirect) {
    vueRoute.redirect = {
      name: children[0].name
    };
  }

  if (children?.length) {
    const childRoutes = children.flatMap(child => transformElegantRouteToVueRoute(child, layouts, views));

    if(isFirstLevelRoute(route)) {
      vueRoute.children = childRoutes;
    } else {
      vueRoutes.push(...childRoutes);
    }
  }

  vueRoutes.unshift(vueRoute);

  return vueRoutes;
}

/**
 * map of route name and route path
 */
const routeMap: RouteMap = {
  "root": "/",
  "not-found": "/:pathMatch(.*)*",
  "403": "/403",
  "404": "/404",
  "500": "/500",
  "dashboard": "/dashboard",
  "group-detail": "/group-detail/:gId",
  "iframe-page": "/iframe-page/:url",
  "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?",
  "ops": "/ops",
  "ops_announcements-list": "/ops/announcements-list",
  "ops_announcements-send": "/ops/announcements-send",
  "ops_api-monitor": "/ops/api-monitor",
  "ops_client-versions": "/ops/client-versions",
  "ops_feedback": "/ops/feedback",
  "ops_friend-backfill": "/ops/friend-backfill",
  "ops_official-accounts": "/ops/official-accounts",
  "ops_splash": "/ops/splash",
  "ops_wallet-notice": "/ops/wallet-notice",
  "privacy": "/privacy",
  "privacy_album": "/privacy/album",
  "privacy_contacts": "/privacy/contacts",
  "privacy_stats": "/privacy/stats",
  "risk": "/risk",
  "risk_complaints": "/risk/complaints",
  "risk_devices": "/risk/devices",
  "risk_group-logs": "/risk/group-logs",
  "risk_groups-index": "/risk/groups-index",
  "risk_messages": "/risk/messages",
  "risk_relations": "/risk/relations",
  "system": "/system",
  "system_admin-login-logs": "/system/admin-login-logs",
  "system_advanced": "/system/advanced",
  "system_audit-logs": "/system/audit-logs",
  "system_config": "/system/config",
  "system_profile": "/system/profile",
  "user-detail": "/user-detail/:userUid",
  "users": "/users",
  "users_generation-tasks": "/users/generation-tasks",
  "users_login-records": "/users/login-records",
  "users-index": "/users-index",
  "wallet": "/wallet",
  "wallet_currencies": "/wallet/currencies",
  "wallet_exchange-config": "/wallet/exchange-config",
  "wallet_exchanges": "/wallet/exchanges",
  "wallet_fee-config": "/wallet/fee-config",
  "wallet_ledger": "/wallet/ledger",
  "wallet_life-payments": "/wallet/life-payments",
  "wallet_life-payments_orders": "/wallet/life-payments/orders",
  "wallet_life-payments_providers": "/wallet/life-payments/providers",
  "wallet_life-payments_tasks": "/wallet/life-payments/tasks",
  "wallet_life-payments_workers": "/wallet/life-payments/workers",
  "wallet_limit-config": "/wallet/limit-config",
  "wallet_recharges": "/wallet/recharges",
  "wallet_red-packets": "/wallet/red-packets",
  "wallet_sweep-logs": "/wallet/sweep-logs",
  "wallet_transfers": "/wallet/transfers",
  "wallet_treasury": "/wallet/treasury",
  "wallet_withdraws": "/wallet/withdraws"
};

/**
 * get route path by route name
 * @param name route name
 */
export function getRoutePath<T extends RouteKey>(name: T) {
  return routeMap[name];
}

/**
 * get route name by route path
 * @param path route path
 */
export function getRouteName(path: RoutePath) {
  const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];

  const routeName: RouteKey | null = routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;

  return routeName;
}
