/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "dashboard": "/dashboard";
    "group-detail": "/group-detail/:gId";
    "iframe-page": "/iframe-page/:url";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "ops": "/ops";
    "ops_announcements-list": "/ops/announcements-list";
    "ops_announcements-send": "/ops/announcements-send";
    "ops_api-monitor": "/ops/api-monitor";
    "ops_client-versions": "/ops/client-versions";
    "ops_feedback": "/ops/feedback";
    "ops_friend-backfill": "/ops/friend-backfill";
    "ops_official-accounts": "/ops/official-accounts";
    "ops_splash": "/ops/splash";
    "ops_wallet-notice": "/ops/wallet-notice";
    "privacy": "/privacy";
    "privacy_album": "/privacy/album";
    "privacy_contacts": "/privacy/contacts";
    "privacy_stats": "/privacy/stats";
    "risk": "/risk";
    "risk_complaints": "/risk/complaints";
    "risk_devices": "/risk/devices";
    "risk_group-logs": "/risk/group-logs";
    "risk_groups-index": "/risk/groups-index";
    "risk_messages": "/risk/messages";
    "risk_relations": "/risk/relations";
    "system": "/system";
    "system_admin-login-logs": "/system/admin-login-logs";
    "system_advanced": "/system/advanced";
    "system_audit-logs": "/system/audit-logs";
    "system_config": "/system/config";
    "system_profile": "/system/profile";
    "user-detail": "/user-detail/:userUid";
    "users": "/users";
    "users_generation-tasks": "/users/generation-tasks";
    "users_login-records": "/users/login-records";
    "users-index": "/users-index";
    "wallet": "/wallet";
    "wallet_currencies": "/wallet/currencies";
    "wallet_exchange-config": "/wallet/exchange-config";
    "wallet_exchanges": "/wallet/exchanges";
    "wallet_fee-config": "/wallet/fee-config";
    "wallet_ledger": "/wallet/ledger";
    "wallet_life-payments": "/wallet/life-payments";
    "wallet_life-payments_orders": "/wallet/life-payments/orders";
    "wallet_life-payments_providers": "/wallet/life-payments/providers";
    "wallet_life-payments_tasks": "/wallet/life-payments/tasks";
    "wallet_life-payments_workers": "/wallet/life-payments/workers";
    "wallet_limit-config": "/wallet/limit-config";
    "wallet_recharges": "/wallet/recharges";
    "wallet_red-packets": "/wallet/red-packets";
    "wallet_sweep-logs": "/wallet/sweep-logs";
    "wallet_transfers": "/wallet/transfers";
    "wallet_treasury": "/wallet/treasury";
    "wallet_withdraws": "/wallet/withdraws";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "dashboard"
    | "group-detail"
    | "iframe-page"
    | "login"
    | "ops"
    | "privacy"
    | "risk"
    | "system"
    | "user-detail"
    | "users"
    | "users-index"
    | "wallet"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "dashboard"
    | "group-detail"
    | "ops_announcements-list"
    | "ops_announcements-send"
    | "ops_api-monitor"
    | "ops_client-versions"
    | "ops_feedback"
    | "ops_friend-backfill"
    | "ops_official-accounts"
    | "ops_splash"
    | "ops_wallet-notice"
    | "privacy_album"
    | "privacy_contacts"
    | "privacy_stats"
    | "risk_complaints"
    | "risk_devices"
    | "risk_group-logs"
    | "risk_groups-index"
    | "risk_messages"
    | "risk_relations"
    | "system_admin-login-logs"
    | "system_advanced"
    | "system_audit-logs"
    | "system_config"
    | "system_profile"
    | "user-detail"
    | "users-index"
    | "users_generation-tasks"
    | "users_login-records"
    | "wallet_currencies"
    | "wallet_exchange-config"
    | "wallet_exchanges"
    | "wallet_fee-config"
    | "wallet_ledger"
    | "wallet_life-payments_orders"
    | "wallet_life-payments_providers"
    | "wallet_life-payments_tasks"
    | "wallet_life-payments_workers"
    | "wallet_limit-config"
    | "wallet_recharges"
    | "wallet_red-packets"
    | "wallet_sweep-logs"
    | "wallet_transfers"
    | "wallet_treasury"
    | "wallet_withdraws"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
