-- Robot sync dedicated schema for jiqiren database.
-- Usage: mysql -h127.0.0.1 -ujiqiren -p jiqiren < scripts/migrate-robot-sync.sql

CREATE TABLE IF NOT EXISTS robot_sync_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    event_id VARCHAR(255) NOT NULL,
    protocol_version VARCHAR(20) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    player_group_id VARCHAR(255) NOT NULL,
    statistics_group_id VARCHAR(255) NOT NULL,
    entity_id VARCHAR(255) NOT NULL,
    business_timestamp BIGINT NOT NULL,
    business_timezone VARCHAR(20) NOT NULL,
    source_updated_at BIGINT NOT NULL,
    sync_reason VARCHAR(100) NOT NULL,
    request_body LONGTEXT NOT NULL,
    process_status VARCHAR(30) NOT NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at DATETIME NULL,
    UNIQUE KEY uk_robot_sync_event_id (event_id),
    KEY idx_robot_sync_entity (player_group_id, entity_id),
    KEY idx_robot_sync_type_time (event_type, business_timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS robot_player_snapshot (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    player_group_id VARCHAR(255) NOT NULL,
    database_generation VARCHAR(100) NOT NULL DEFAULT 'gen-1',
    statistics_group_id VARCHAR(255) NOT NULL,
    wxid VARCHAR(255) NOT NULL,
    player_no VARCHAR(100) NULL,
    nickname VARCHAR(255) NULL,
    display_name VARCHAR(255) NULL,
    remark VARCHAR(255) NULL,
    player_type VARCHAR(20) NULL,
    balance DECIMAL(20,4) NOT NULL DEFAULT 0,
    direct_parent_wxid VARCHAR(255) NULL,
    direct_parent_no VARCHAR(100) NULL,
    parent_path TEXT NULL,
    level_no INT NOT NULL DEFAULT 1,
    active TINYINT(1) NOT NULL DEFAULT 1,
    total_flow DECIMAL(20,4) NOT NULL DEFAULT 0,
    used_flow DECIMAL(20,4) NOT NULL DEFAULT 0,
    remaining_flow DECIMAL(20,4) NOT NULL DEFAULT 0,
    total_up DECIMAL(20,4) NOT NULL DEFAULT 0,
    total_down DECIMAL(20,4) NOT NULL DEFAULT 0,
    total_profit_loss DECIMAL(20,4) NOT NULL DEFAULT 0,
    rebate_rate DECIMAL(20,4) NOT NULL DEFAULT 0,
    rebate_rate_unit VARCHAR(30) NOT NULL DEFAULT 'per_10000',
    total_rebate DECIMAL(20,4) NOT NULL DEFAULT 0,
    source_updated_at BIGINT NOT NULL,
    last_event_id VARCHAR(255) NOT NULL,
    last_sync_reason VARCHAR(100) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_robot_player_gen (player_group_id, database_generation, wxid),
    KEY idx_robot_player_no (player_group_id, player_no),
    KEY idx_robot_player_parent (player_group_id, direct_parent_wxid),
    KEY idx_robot_player_type (player_group_id, player_type),
    KEY idx_robot_player_gen (player_group_id, database_generation, active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS robot_player_daily_summary (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    event_id VARCHAR(255) NOT NULL,
    player_group_id VARCHAR(255) NOT NULL,
    statistics_group_id VARCHAR(255) NOT NULL,
    business_date DATE NOT NULL,
    business_timestamp BIGINT NOT NULL,
    wxid VARCHAR(255) NOT NULL,
    player_no VARCHAR(100) NULL,
    nickname VARCHAR(255) NULL,
    display_name VARCHAR(255) NULL,
    remark VARCHAR(255) NULL,
    player_type VARCHAR(20) NULL,
    balance DECIMAL(20,4) NOT NULL DEFAULT 0,
    direct_parent_wxid VARCHAR(255) NULL,
    direct_parent_no VARCHAR(100) NULL,
    parent_path TEXT NULL,
    level_no INT NOT NULL DEFAULT 1,
    active TINYINT(1) NOT NULL DEFAULT 1,
    total_flow DECIMAL(20,4) NOT NULL DEFAULT 0,
    used_flow DECIMAL(20,4) NOT NULL DEFAULT 0,
    remaining_flow DECIMAL(20,4) NOT NULL DEFAULT 0,
    pending_rebate DECIMAL(20,4) NOT NULL DEFAULT 0,
    total_up DECIMAL(20,4) NOT NULL DEFAULT 0,
    total_down DECIMAL(20,4) NOT NULL DEFAULT 0,
    total_profit_loss DECIMAL(20,4) NOT NULL DEFAULT 0,
    rebate_rate DECIMAL(20,4) NOT NULL DEFAULT 0,
    rebate_rate_unit VARCHAR(30) NOT NULL DEFAULT 'per_10000',
    total_rebate DECIMAL(20,4) NOT NULL DEFAULT 0,
    sync_reason VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_robot_daily_event (event_id),
    KEY idx_robot_daily_player (player_group_id, wxid, business_date),
    KEY idx_robot_daily_date (player_group_id, business_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
