CREATE TABLE IF NOT EXISTS user_location_latest (
  user_id VARCHAR(10) NOT NULL,
  device_id VARCHAR(64) NULL,
  latitude DOUBLE NOT NULL,
  longitude DOUBLE NOT NULL,
  accuracy DOUBLE NULL,
  altitude DOUBLE NULL,
  heading DOUBLE NULL,
  speed DOUBLE NULL,
  source VARCHAR(16) NULL,
  geohash VARCHAR(16) NULL,
  country VARCHAR(64) NULL,
  province VARCHAR(64) NULL,
  city VARCHAR(64) NULL,
  district VARCHAR(64) NULL,
  city_label VARCHAR(128) NULL,
  collected_at DATETIME(6) NOT NULL,
  server_received_at DATETIME(6) NOT NULL,
  ip VARCHAR(64) NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (user_id),
  KEY idx_user_location_collected (collected_at),
  KEY idx_user_location_geohash (geohash)
);
