CREATE TABLE IF NOT EXISTS app_splash_config (
  id BIGINT NOT NULL AUTO_INCREMENT,
  version VARCHAR(32) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  image_url VARCHAR(1000) NULL,
  image_md5 CHAR(32) NULL,
  content_type VARCHAR(64) NULL,
  width INT NULL,
  height INT NULL,
  bytes INT NULL,
  fit VARCHAR(32) NOT NULL DEFAULT 'cover',
  start_at DATETIME(6) NULL,
  end_at DATETIME(6) NULL,
  min_app_version VARCHAR(32) NULL,
  platforms VARCHAR(128) NULL COMMENT 'comma-separated; empty=all',
  channels VARCHAR(256) NULL COMMENT 'comma-separated; empty=all',
  object_key VARCHAR(500) NULL,
  created_by VARCHAR(64) NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_app_splash_version (version),
  KEY idx_app_splash_enabled_updated (enabled, updated_at)
);
